# -*- coding: utf-8 -*-
"""sixphase(03.02.24).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qBF-5kMUuwtUzThJf8YCUmVrq3hs00Dw
"""

# class task
#  Build decision tree model to predict survival based on certain parameters

import pandas as pd
import numpy as np
import sklearn as sklearn

data = pd.read_csv('/content/drive/MyDrive/sixphase/titanic.csv')

from sklearn.tree import DecisionTreeClassifier

print(data.isna().sum())

print(data.head())

data = data.drop(columns = 'Age')

data = data.drop(columns = ["SibSp","Name"])

print(data.head())

data = data.drop(columns = ["PassengerId","Parch","Ticket","Fare","Cabin","Embarked"])

print(data.head())

!pip install word2number

data['Sex'].replace({'male':1, 'female':2}, inplace=True)
print(data)

print(data.corr().to_string)

x = data.drop(columns = ['Survived'])
y = data['Survived']
print(x.to_string())
print(y.to_string())

"""# DECISION TREE"""

model_before = DecisionTreeClassifier()
model_before.fit(x,y)

print(model_before.score(x,y))

from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.09)

model = DecisionTreeClassifier()
model.fit(x_train,y_train)

print(model.score(x_train,y_train))



"""# LOGISTIC REGRESSION"""

from sklearn.linear_model import LogisticRegression

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.09)

logmodel = LogisticRegression()
logmodel.fit(x_train,y_train)

print(model.score(x_train,y_train))



"""# LINEAR REGRESSION"""

from sklearn.linear_model import LinearRegression

modellin = LinearRegression()
modellin.fit(x_train,y_train)

print(modellin.score(x_train,y_train))



"""# ****"""